version: "3.7"
services:
  #Laravel Service
  app:
    container_name: laravel_app
    restart: always
    tty: true
    working_dir: /var/www/app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      XDEBUG_CONFIG: "idekey=IDE_DEBUG"
      PHP_IDE_CONFIG: "serverName=laravel_app"
#    ports:
#      - 9001:9000
#      - 9002:9001
    volumes:
      - .:/var/www/app
    depends_on:
      - database
    links:
      - database
    networks:
      - laravel_network

  #DB Service
  database:
    image: mysql:8.0
    container_name: laravel_database
    restart: always
    working_dir: /etc/mysql
    tty: true
    environment:
      MYSQL_DATABASE: laratest
      MYSQL_USER: avinash
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: avinash
    ports:
      - 9908:3306
    volumes:
      - "./data:/var/lib/mysql"
      - "./mysql-files:/var/lib/mysql-files"
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - laravel_network

  #Nginx Service
  server:
    image: nginx:alpine
    container_name: laravel_react_server
    restart: always
    tty: true
    ports:
      - 8100:8080
    volumes:
      - .:/var/www/app
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
    networks:
      - laravel_network

#Docker Networks
networks:
  laravel_network:
    driver: bridge
volumes:
  dbdata:
    driver: local
